# Generated by Django 3.1.1 on 2022-06-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
